[project]
name = "image-board"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "django>=5.2",
    "django-stubs>=5.2.0",
    "psycopg[binary]>=3.2.6",
    "pydantic>=2.11.3",
]
