# Generated by Django 5.2 on 2025-04-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
